DROP DATABASE IF EXISTS CINEMATRIX;
CREATE DATABASE CINEMATRIX CHARSET = UTF8 COLLATE = UTF8_UNICODE_CI;
USE CINEMATRIX;

CREATE TABLE PAIS(
ID_PAIS INT PRIMARY KEY AUTO_INCREMENT											COMMENT 'CAMPO LLAVE PRIMARIA, SE INCREMENTA AUTOMATICAMENTE',
ISO CHAR(2) NOT NULL,			
PAIS VARCHAR(50) NOT NULL														COMMENT 'CAMPO QUE ALMACENA EL NOMBRE DEL PAIS'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE USUARIO(
ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'CAMPO LLAVE PRIMARIA, SE INCREMENTA AUTOMATICAMENTE',					
NOMBRE VARCHAR(20) NOT NULL														COMMENT 'CAMPO QUE ALMACENA EL NOMBRE DEL USUARIO',
APELLIDO VARCHAR(20) NOT NULL													COMMENT 'CAMPO QUE ALMACENA EL APELLIDO DEL USUARIO',
CORREO VARCHAR(40) NOT NULL														COMMENT 'CAMPO QUE ALMACENA EL CORREO DEL USUARIO',
SEXO VARCHAR(10) NOT NULL														COMMENT 'CAMPO QUE ALMACENA EL SEXO DEL USUARIO',
TELEFONO INT(20) NOT NULL														COMMENT 'CAMPO QUE ALMACENA EL TELEFONO DEL USUARIO',
FECHA_NACIMIENTO DATE NOT NULL													COMMENT 'CAMPO QUE ALMACENA LA FECHA DE NACIMIENTO DEL USUARIO',
ID_PAIS INT																		COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA PAIS',
CIUDAD VARCHAR(30) NOT NULL														COMMENT 'CAMPO QUE ALMACENA LA CIUDAD DEL USUARIO',
FOTO_PERFIL MEDIUMBLOB,
CONSTRAINT USER_ID_PAIS_FK FOREIGN KEY (id_pais) REFERENCES PAIS (ID_PAIS)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE ROLES(
ID_ROL INT PRIMARY KEY AUTO_INCREMENT											COMMENT 'CAMPO LLAVE PRIMARIA, SE INCREMENTA AUTOMATICAMENTE',
NOMBRE VARCHAR(15) NOT NULL														COMMENT 'REGISTRA EL NOMBRE DEL ROL'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE LOGIN(
ID_LOGIN INT PRIMARY KEY AUTO_INCREMENT											COMMENT 'LLAVE PRIMARIA, QUE ALMACENA UN ID DE REGISTRO, SE INCREMENTA AUMATICAMENTE',
ID_USUARIO INT																	COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA USUARIO',
ID_ROL INT																		COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA ROL',
CORREO VARCHAR(40) NOT NULL														COMMENT 'CAMPO QUE ALMACENA EL CORREO DEL USUARIO',
CONTRASEÑA VARCHAR(50) NOT NULL													COMMENT 'CAMPO QUE ALMACENA LA CONTRASEÑA DEL USUARIO',
FECHA_CREACION DATETIME NOT NULL												COMMENT 'CAMPO QUE ALMACENA LA FECHA DE CREACIÓN DEL REGISTRO',
CONSTRAINT LOGIN_USER_ID_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
CONSTRAINT LOGIN_ID_ROL_FK FOREIGN KEY (ID_ROL) REFERENCES ROLES (ID_ROL)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE FACTURA(
ID_FACTURA INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'LLAVE PRIMARIA, SE INCREMENTA AUTOMATICAMENTE',
ID_USUARIO INT																	COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA AL USUARIO',
FECHA DATETIME NOT NULL															COMMENT 'CAMPO QUE DESCRIBE LA CANTIDAD DE ASIENTOS',
METODO_PAGO VARCHAR(20) NOT NULL												COMMENT 'CAMPO QUE DESCRIBE EL TIPO DE PAGO REALIZADO',
PROMOCION VARCHAR(20)															COMMENT 'CAMPO QUE DESCRIBE EL TIPO DE PROMOCION',
DESCUENTO FLOAT(1.2)															COMMENT 'CAMPO QUE DESCRIBE EL % DE DESCUENTO APLICADO',
SUBTOTAL INT NOT NULL															COMMENT 'CAMPO QUE MUESTRA EL SUBTOTAL DE LA COMPRA',
TOTAL INT NOT NULL																COMMENT 'CAMPO QUE MUESTRA EL TOTAL DE LA COMPRA',
CONSTRAINT FACTURA_ID_USER_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE ESTADO(
ID_ESTADO INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'LLAVE PRIMARIA, SE INCREMENTA AUTOMATICAMENTE',
DESCRIPCION VARCHAR(30) NOT NULL												COMMENT 'CAMPO QUE DESCRIBE UN ESTADO, EJEMPLO: ACTIVO/INACTIVO, DISPONIBLE/OCUPADO'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE CLASIFICACION(
ID_CLASIFICACION INT PRIMARY KEY AUTO_INCREMENT									COMMENT 'LLAVE PRIMARIA, SE INCREMENTA AUTOMATICAMENTE',
CLASIFICACION VARCHAR(5) NOT NULL												COMMENT 'CLASIFICACION DE LA PELICULA',
DESCRIPCION VARCHAR(100) NOT NULL												COMMENT 'CAMPO QUE DESCRIBE LA CLASIFICACION'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE GENERO(
ID_GENERO INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'LLAVE PRIMARIA, SE INCREMENTA AUTOMATICAMENTE',		
GENERO VARCHAR(30) NOT NULL														COMMENT 'CAMPO NOMBRE DE GENERO'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE PELICULA(
ID_PELICULA INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'LLAVE PRIMARIA, SE INCREMENTA AUTOMATICAMENTE',
TITULO VARCHAR(30) NOT NULL														COMMENT 'CAMPO QUE ALMACENA EL TITULO DE LA PELICULA',
SINOPSIS TEXT NOT NULL															COMMENT 'BREVE DESCRIPCION DE LA PELICULA',
DURACION TIME NOT NULL															COMMENT 'CAMPO QUE ESPECIFICA LA DURACIÓN DE LA PELICULA',
REPARTO VARCHAR(100) NOT NULL,
DIRECTOR VARCHAR(100) NOT NULL,
AÑO YEAR NOT NULL																COMMENT 'CAMPO QUE DESCRIBE EL AÑO DE LA PELICULA',
ID_GENERO INT																	COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA GENERO',
ID_CLASIFICACION INT															COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA CLASIFICACION',
PORTADA VARCHAR(200)															COMMENT 'IMAGEN DE LA PELICULA',				
ID_ESTADO INT																	COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA ESTADO',
CONSTRAINT PELICULA_ID_GENERO_FK FOREIGN KEY (ID_GENERO) REFERENCES GENERO (ID_GENERO),
CONSTRAINT PELICULA_ID_CLASIFICACION_FK FOREIGN KEY (ID_CLASIFICACION) REFERENCES CLASIFICACION (ID_CLASIFICACION),
CONSTRAINT PELICULA_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IDIOMA(
ID_IDIOMA INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'LLAVE PRIMERIA, SE INCREMENTA AUTOMATICAMENTE',	
NOMBRE VARCHAR(25) NOT NULL														COMMENT 'IDIOMA PELICULA'			
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE FORMATO(
ID_FORMATO INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'LLAVE PRIMERIA, SE INCREMENTA AUTOMATICAMENTE',
FORMATO VARCHAR(25) NOT NULL													COMMENT 'CAMPO QUE ALMACENA EL FORMATO DE LA PELICULA EJEMPLO: 2D, 3D'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE SALA(
ID_SALA INT PRIMARY KEY AUTO_INCREMENT											COMMENT 'LLAVE PRIMERIA, SE INCREMENTA AUTOMATICAMENTE',
NOMBRE VARCHAR(10) NOT NULL														COMMENT 'CAMPO QUE DESCRIBE EL NOMBRE DE LA SALA',
DESCRIPCION VARCHAR(30) NOT NULL												COMMENT 'DESCRIPCIÓN DE LA SALA',
CANT_ASIENTOS INT NOT NULL														COMMENT 'CAMPO QUE DESCRIBE LA CANTIDAD DE ASIENTOS DE LA SALA',
ID_ESTADO INT																	COMMENT 'LLAVE FORANEA, QUE HACE REFERENCIA A LA TABLA ESTADO',
CONSTRAINT SALA_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE CARTELERA(
ID_CARTELERA INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'LLAVE PRIMERIA, SE INCREMENTA AUTOMATICAMENTE',
ID_PELICULA INT																	COMMENT 'LLAVE FORANEA, QUE HACE REFERENCIA A LA TABLA PELICULA',
ID_SALA INT																		COMMENT 'LLAVE FORANEA, QUE HACE REFERENCIA A LA TABLA SALA',
HORA_INICIO TIME NOT NULL														COMMENT 'CAMPO QUE MUESTRA LA HORA DE INICIO DE LA PELICULA',
HORA_FIN TIME NOT NULL															COMMENT 'CAMPO QUE MUESTRA LA HORA FIN DE LA PELICULA',
ID_IDIOMA INT																	COMMENT 'LLAVE FORANEA, QUE HACE REFERENCIA A LA TABLA IDIOMA',
ID_FORMATO INT																	COMMENT 'LLAVE FORANEA, QUE HACE REFERENCIA A LA TABLA FORMATO',
FECHA DATE NOT NULL																COMMENT 'CAMPO QUE DESCRIBE LA FECHA DE LA PELICULA',
CONSTRAINT CARTELERA_ID_PELICULA_FK FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA (ID_PELICULA),
CONSTRAINT CARTELERA_ID_SALA_FK FOREIGN KEY (ID_SALA) REFERENCES SALA (ID_SALA),
CONSTRAINT CARTELERA_ID_IDIOMA_FK FOREIGN KEY (ID_IDIOMA) REFERENCES IDIOMA (ID_IDIOMA),
CONSTRAINT CARTELERA_ID_FORMATO_FK FOREIGN KEY (ID_FORMATO) REFERENCES FORMATO (ID_FORMATO)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE ASIENTO(
ID_ASIENTO INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'LLAVE PRIMERIA, SE INCREMENTA AUTOMATICAMENTE',
NUM_ASIENTO VARCHAR(5) NOT NULL													COMMENT 'CAMPO QUE DESCRIBE EL NUMERO DEL ASIENTO EJEMPLO: A10, K17,  ETC',	
ID_SALA INT																		COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA SALA',
ID_ESTADO INT																	COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA ESTADO',
CONSTRAINT ASIENTO_ID_SALA_FK FOREIGN KEY (ID_SALA) REFERENCES SALA (ID_SALA),
CONSTRAINT ASIENTO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE CATEGORIA_PROMO(
ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE PROMOCION(
ID_PROMO INT PRIMARY KEY AUTO_INCREMENT											COMMENT 'LLAVE PRIMERIA, SE INCREMENTA AUTOMATICAMENTE',
NOMBRE VARCHAR (50) NOT NULL													COMMENT 'DESCRIBRE EL NOMBRE DE LA PROMOCION, EJEMPLO: 2X1, 3X1, ETC',
DESCRIPCION TEXT NOT NULL,
ID_CATEGORIA INT,
PRECIO FLOAT (3.2) NOT NULL,
IMAGEN VARCHAR(200),
CONSTRAINT PROMOCION_ID_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_PROMO (ID_CATEGORIA)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE PROGRAMACION_PROMO(
ID_PPROMO INT PRIMARY KEY AUTO_INCREMENT										COMMENT 'LLAVE PRIMERIA, SE INCREMENTA AUTOMATICAMENTE',
ID_PROMO INT																	COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA PROMOCION',
FECHA_INICIO DATE NOT NULL														COMMENT 'CAMPO QUE DESCRIBE LAS FECHAS DE PROMOCIÓN',
FECHA_FIN DATE NOT NULL,
ID_ESTADO INT																	COMMENT 'LLAVE FORANEA QUE HACE REFERENCIA A LA TABLA ESTADO',
CONSTRAINT PROGRAMACIONP_ID_PROMO_FK FOREIGN KEY (ID_PROMO) REFERENCES PROMOCION (ID_PROMO),
CONSTRAINT PROGRAMACIONP_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE BOLETO(
ID_BOLETO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION TEXT NOT NULL,
PRECIO FLOAT(3.2) NOT NULL
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE COMBO(
ID_COMBO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION TEXT NOT NULL,
PRECIO FLOAT(3.2) NOT NULL,
IMAGEN VARCHAR(200)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;

CREATE TABLE DETALLE(
ID_DETALLE INT PRIMARY KEY AUTO_INCREMENT,
ID_FACTURA INT,
ID_CARTELERA INT,
ID_BOLETO INT,
ID_COMBO INT,
BUTACA VARCHAR(30),
CONSTRAINT DETALLE_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA (ID_FACTURA),
CONSTRAINT DETALLE_ID_CARTELERA_FK FOREIGN KEY (ID_CARTELERA) REFERENCES CARTELERA (ID_CARTELERA),
CONSTRAINT DETALLE_ID_BOLETO_FK FOREIGN KEY (ID_BOLETO) REFERENCES BOLETO (ID_BOLETO),
CONSTRAINT DETALLE_ID_COMBO_FK FOREIGN KEY (ID_COMBO) REFERENCES COMBO (ID_COMBO)
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE=UTF8_UNICODE_CI;
