-- INSERCIONES

-- ROLES
INSERT INTO ROLES(NOMBRE) VALUES('Administrador');
INSERT INTO ROLES(NOMBRE) VALUES('Cliente');

-- PAIS
INSERT INTO PAIS(ISO, PAIS) VALUES('AF', 'Afganistán');
INSERT INTO PAIS(ISO, PAIS) VALUES('AX', 'Islas Gland');
INSERT INTO PAIS(ISO, PAIS) VALUES('AL', 'Albania');
INSERT INTO PAIS(ISO, PAIS) VALUES('DE', 'Alemania');
INSERT INTO PAIS(ISO, PAIS) VALUES('AD', 'Andorra');
INSERT INTO PAIS(ISO, PAIS) VALUES('AO', 'Angola');
INSERT INTO PAIS(ISO, PAIS) VALUES('AI', 'Anguilla');
INSERT INTO PAIS(ISO, PAIS) VALUES('AQ', 'Antártida');
INSERT INTO PAIS(ISO, PAIS) VALUES('AG', 'Antigua y Barbuda');
INSERT INTO PAIS(ISO, PAIS) VALUES('AN', 'Antillas Holandesas');
INSERT INTO PAIS(ISO, PAIS) VALUES('SA', 'Arabia Saudí');
INSERT INTO PAIS(ISO, PAIS) VALUES('DZ', 'Argelia');
INSERT INTO PAIS(ISO, PAIS) VALUES('AR', 'Argentina');
INSERT INTO PAIS(ISO, PAIS) VALUES('AM', 'Armenia');
INSERT INTO PAIS(ISO, PAIS) VALUES('AW', 'Aruba');
INSERT INTO PAIS(ISO, PAIS) VALUES('AU', 'Australia');
INSERT INTO PAIS(ISO, PAIS) VALUES('AT', 'Austria');
INSERT INTO PAIS(ISO, PAIS) VALUES('AZ', 'Azerbaiyán');
INSERT INTO PAIS(ISO, PAIS) VALUES('BS', 'Bahamas');
INSERT INTO PAIS(ISO, PAIS) VALUES('BH', 'Bahréin');
INSERT INTO PAIS(ISO, PAIS) VALUES('BD', 'Bangladesh');
INSERT INTO PAIS(ISO, PAIS) VALUES('BB', 'Barbados');
INSERT INTO PAIS(ISO, PAIS) VALUES('BY', 'Bielorrusia');
INSERT INTO PAIS(ISO, PAIS) VALUES('BE', 'Bélgica');
INSERT INTO PAIS(ISO, PAIS) VALUES('BZ', 'Belice');
INSERT INTO PAIS(ISO, PAIS) VALUES('BJ', 'Benin');
INSERT INTO PAIS(ISO, PAIS) VALUES('BM', 'Bermudas');
INSERT INTO PAIS(ISO, PAIS) VALUES('BT', 'Bhután');
INSERT INTO PAIS(ISO, PAIS) VALUES('BO', 'Bolivia');
INSERT INTO PAIS(ISO, PAIS) VALUES('BA', 'Bosnia y Herzegovina');
INSERT INTO PAIS(ISO, PAIS) VALUES('BW', 'Botsuana');
INSERT INTO PAIS(ISO, PAIS) VALUES('BV', 'Isla Bouvet');
INSERT INTO PAIS(ISO, PAIS) VALUES('BR', 'Brasil');
INSERT INTO PAIS(ISO, PAIS) VALUES('BN', 'Brunéi');
INSERT INTO PAIS(ISO, PAIS) VALUES('BG', 'Bulgaria');
INSERT INTO PAIS(ISO, PAIS) VALUES('BF', 'Burkina Faso');
INSERT INTO PAIS(ISO, PAIS) VALUES('BI', 'Burundi');
INSERT INTO PAIS(ISO, PAIS) VALUES('CV', 'Cabo Verde');
INSERT INTO PAIS(ISO, PAIS) VALUES('KY', 'Islas Caimán');
INSERT INTO PAIS(ISO, PAIS) VALUES('KH', 'Camboya');
INSERT INTO PAIS(ISO, PAIS) VALUES('CM', 'Camerún');
INSERT INTO PAIS(ISO, PAIS) VALUES('CA', 'Canadá');
INSERT INTO PAIS(ISO, PAIS) VALUES('CF', 'República Centroafricana');
INSERT INTO PAIS(ISO, PAIS) VALUES('TD', 'Chad');
INSERT INTO PAIS(ISO, PAIS) VALUES('CZ', 'República Checa');
INSERT INTO PAIS(ISO, PAIS) VALUES('CL', 'Chile');
INSERT INTO PAIS(ISO, PAIS) VALUES('CN', 'China');
INSERT INTO PAIS(ISO, PAIS) VALUES('CY', 'Chipre');
INSERT INTO PAIS(ISO, PAIS) VALUES('CX', 'Isla de Navidad');
INSERT INTO PAIS(ISO, PAIS) VALUES('VA', 'Ciudad del Vaticano');
INSERT INTO PAIS(ISO, PAIS) VALUES('CC', 'Islas Cocos');
INSERT INTO PAIS(ISO, PAIS) VALUES('CO', 'Colombia');
INSERT INTO PAIS(ISO, PAIS) VALUES('KM', 'Comoras');
INSERT INTO PAIS(ISO, PAIS) VALUES('CD', 'República Democrática del Congo');
INSERT INTO PAIS(ISO, PAIS) VALUES('CG', 'Congo');
INSERT INTO PAIS(ISO, PAIS) VALUES('CK', 'Islas Cook');
INSERT INTO PAIS(ISO, PAIS) VALUES('KP', 'Corea del Norte');
INSERT INTO PAIS(ISO, PAIS) VALUES('KR', 'Corea del Sur');
INSERT INTO PAIS(ISO, PAIS) VALUES('CI', 'Costa de Marfil');
INSERT INTO PAIS(ISO, PAIS) VALUES('CR', 'Costa Rica');
INSERT INTO PAIS(ISO, PAIS) VALUES('HR', 'Croacia');
INSERT INTO PAIS(ISO, PAIS) VALUES('CU', 'Cuba');
INSERT INTO PAIS(ISO, PAIS) VALUES('DK', 'Dinamarca');
INSERT INTO PAIS(ISO, PAIS) VALUES('DM', 'Dominica');
INSERT INTO PAIS(ISO, PAIS) VALUES('DO', 'República Dominicana');
INSERT INTO PAIS(ISO, PAIS) VALUES('EC', 'Ecuador');
INSERT INTO PAIS(ISO, PAIS) VALUES('EG', 'Egipto');
INSERT INTO PAIS(ISO, PAIS) VALUES('SV', 'El Salvador');
INSERT INTO PAIS(ISO, PAIS) VALUES('AE', 'Emiratos Árabes Unidos');
INSERT INTO PAIS(ISO, PAIS) VALUES('ER', 'Eritrea');
INSERT INTO PAIS(ISO, PAIS) VALUES('SK', 'Eslovaquia');
INSERT INTO PAIS(ISO, PAIS) VALUES('SI', 'Eslovenia');
INSERT INTO PAIS(ISO, PAIS) VALUES('ES', 'España');
INSERT INTO PAIS(ISO, PAIS) VALUES('UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO PAIS(ISO, PAIS) VALUES('US', 'Estados Unidos');
INSERT INTO PAIS(ISO, PAIS) VALUES('EE', 'Estonia');
INSERT INTO PAIS(ISO, PAIS) VALUES('ET', 'Etiopía');
INSERT INTO PAIS(ISO, PAIS) VALUES('FO', 'Islas Feroe');
INSERT INTO PAIS(ISO, PAIS) VALUES('PH', 'Filipinas');
INSERT INTO PAIS(ISO, PAIS) VALUES('FI', 'Finlandia');
INSERT INTO PAIS(ISO, PAIS) VALUES('FJ', 'Fiyi');
INSERT INTO PAIS(ISO, PAIS) VALUES('FR', 'Francia');
INSERT INTO PAIS(ISO, PAIS) VALUES('GA', 'Gabón');
INSERT INTO PAIS(ISO, PAIS) VALUES('GM', 'Gambia');
INSERT INTO PAIS(ISO, PAIS) VALUES('GE', 'Georgia');
INSERT INTO PAIS(ISO, PAIS) VALUES('GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO PAIS(ISO, PAIS) VALUES('GH', 'Ghana');
INSERT INTO PAIS(ISO, PAIS) VALUES('GI', 'Gibraltar');
INSERT INTO PAIS(ISO, PAIS) VALUES('GD', 'Granada');
INSERT INTO PAIS(ISO, PAIS) VALUES('GR', 'Grecia');
INSERT INTO PAIS(ISO, PAIS) VALUES('GL', 'Groenlandia');
INSERT INTO PAIS(ISO, PAIS) VALUES('GP', 'Guadalupe');
INSERT INTO PAIS(ISO, PAIS) VALUES('GU', 'Guam');
INSERT INTO PAIS(ISO, PAIS) VALUES('GT', 'Guatemala');
INSERT INTO PAIS(ISO, PAIS) VALUES('GF', 'Guayana Francesa');
INSERT INTO PAIS(ISO, PAIS) VALUES('GN', 'Guinea');
INSERT INTO PAIS(ISO, PAIS) VALUES('GQ', 'Guinea Ecuatorial');
INSERT INTO PAIS(ISO, PAIS) VALUES('GW', 'Guinea-Bissau');
INSERT INTO PAIS(ISO, PAIS) VALUES('GY', 'Guyana');
INSERT INTO PAIS(ISO, PAIS) VALUES('HT', 'Haití');
INSERT INTO PAIS(ISO, PAIS) VALUES('HM', 'Islas Heard y McDonald');
INSERT INTO PAIS(ISO, PAIS) VALUES('HN', 'Honduras');
INSERT INTO PAIS(ISO, PAIS) VALUES('HK', 'Hong Kong');
INSERT INTO PAIS(ISO, PAIS) VALUES('HU', 'Hungría');
INSERT INTO PAIS(ISO, PAIS) VALUES('IN', 'India');
INSERT INTO PAIS(ISO, PAIS) VALUES('ID', 'Indonesia');
INSERT INTO PAIS(ISO, PAIS) VALUES('IR', 'Irán');
INSERT INTO PAIS(ISO, PAIS) VALUES('IQ', 'Iraq');
INSERT INTO PAIS(ISO, PAIS) VALUES('IE', 'Irlanda');
INSERT INTO PAIS(ISO, PAIS) VALUES('IS', 'Islandia');
INSERT INTO PAIS(ISO, PAIS) VALUES('IL', 'Israel');
INSERT INTO PAIS(ISO, PAIS) VALUES('IT', 'Italia');
INSERT INTO PAIS(ISO, PAIS) VALUES('JM', 'Jamaica');
INSERT INTO PAIS(ISO, PAIS) VALUES('JP', 'Japón');
INSERT INTO PAIS(ISO, PAIS) VALUES('JO', 'Jordania');
INSERT INTO PAIS(ISO, PAIS) VALUES('KZ', 'Kazajstán');
INSERT INTO PAIS(ISO, PAIS) VALUES('KE', 'Kenia');
INSERT INTO PAIS(ISO, PAIS) VALUES('KG', 'Kirguistán');
INSERT INTO PAIS(ISO, PAIS) VALUES('KI', 'Kiribati');
INSERT INTO PAIS(ISO, PAIS) VALUES('KW', 'Kuwait');
INSERT INTO PAIS(ISO, PAIS) VALUES('LA', 'Laos');
INSERT INTO PAIS(ISO, PAIS) VALUES('LS', 'Lesotho');
INSERT INTO PAIS(ISO, PAIS) VALUES('LV', 'Letonia');
INSERT INTO PAIS(ISO, PAIS) VALUES('LB', 'Líbano');
INSERT INTO PAIS(ISO, PAIS) VALUES('LR', 'Liberia');
INSERT INTO PAIS(ISO, PAIS) VALUES('LY', 'Libia');
INSERT INTO PAIS(ISO, PAIS) VALUES('LI', 'Liechtenstein');
INSERT INTO PAIS(ISO, PAIS) VALUES('LT', 'Lituania');
INSERT INTO PAIS(ISO, PAIS) VALUES('LU', 'Luxemburgo');
INSERT INTO PAIS(ISO, PAIS) VALUES('MO', 'Macao');
INSERT INTO PAIS(ISO, PAIS) VALUES('MK', 'ARY Macedonia');
INSERT INTO PAIS(ISO, PAIS) VALUES('MG', 'Madagascar');
INSERT INTO PAIS(ISO, PAIS) VALUES('MY', 'Malasia');
INSERT INTO PAIS(ISO, PAIS) VALUES('MW', 'Malawi');
INSERT INTO PAIS(ISO, PAIS) VALUES('MV', 'Maldivas');
INSERT INTO PAIS(ISO, PAIS) VALUES('ML', 'Malí');
INSERT INTO PAIS(ISO, PAIS) VALUES('MT', 'Malta');
INSERT INTO PAIS(ISO, PAIS) VALUES('FK', 'Islas Malvinas');
INSERT INTO PAIS(ISO, PAIS) VALUES('MP', 'Islas Marianas del Norte');
INSERT INTO PAIS(ISO, PAIS) VALUES('MA', 'Marruecos');
INSERT INTO PAIS(ISO, PAIS) VALUES('MH', 'Islas Marshall');
INSERT INTO PAIS(ISO, PAIS) VALUES('MQ', 'Martinica');
INSERT INTO PAIS(ISO, PAIS) VALUES('MU', 'Mauricio');
INSERT INTO PAIS(ISO, PAIS) VALUES('MR', 'Mauritania');
INSERT INTO PAIS(ISO, PAIS) VALUES('YT', 'Mayotte');
INSERT INTO PAIS(ISO, PAIS) VALUES('MX', 'México');
INSERT INTO PAIS(ISO, PAIS) VALUES('FM', 'Micronesia');
INSERT INTO PAIS(ISO, PAIS) VALUES('MD', 'Moldavia');
INSERT INTO PAIS(ISO, PAIS) VALUES('MC', 'Mónaco');
INSERT INTO PAIS(ISO, PAIS) VALUES('MN', 'Mongolia');
INSERT INTO PAIS(ISO, PAIS) VALUES('MS', 'Montserrat');
INSERT INTO PAIS(ISO, PAIS) VALUES('MZ', 'Mozambique');
INSERT INTO PAIS(ISO, PAIS) VALUES('MM', 'Myanmar');
INSERT INTO PAIS(ISO, PAIS) VALUES('NA', 'Namibia');
INSERT INTO PAIS(ISO, PAIS) VALUES('NR', 'Nauru');
INSERT INTO PAIS(ISO, PAIS) VALUES('NP', 'Nepal');
INSERT INTO PAIS(ISO, PAIS) VALUES('NI', 'Nicaragua');
INSERT INTO PAIS(ISO, PAIS) VALUES('NE', 'Níger');
INSERT INTO PAIS(ISO, PAIS) VALUES('NG', 'Nigeria');
INSERT INTO PAIS(ISO, PAIS) VALUES('NU', 'Niue');
INSERT INTO PAIS(ISO, PAIS) VALUES('NF', 'Isla Norfolk');
INSERT INTO PAIS(ISO, PAIS) VALUES('NO', 'Noruega');
INSERT INTO PAIS(ISO, PAIS) VALUES('NC', 'Nueva Caledonia');
INSERT INTO PAIS(ISO, PAIS) VALUES('NZ', 'Nueva Zelanda');
INSERT INTO PAIS(ISO, PAIS) VALUES('OM', 'Omán');
INSERT INTO PAIS(ISO, PAIS) VALUES('NL', 'Países Bajos');
INSERT INTO PAIS(ISO, PAIS) VALUES('PK', 'Pakistán');
INSERT INTO PAIS(ISO, PAIS) VALUES('PW', 'Palau');
INSERT INTO PAIS(ISO, PAIS) VALUES('PS', 'Palestina');
INSERT INTO PAIS(ISO, PAIS) VALUES('PA', 'Panamá');
INSERT INTO PAIS(ISO, PAIS) VALUES('PG', 'Papúa Nueva Guinea');
INSERT INTO PAIS(ISO, PAIS) VALUES('PY', 'Paraguay');
INSERT INTO PAIS(ISO, PAIS) VALUES('PE', 'Perú');
INSERT INTO PAIS(ISO, PAIS) VALUES('PN', 'Islas Pitcairn');
INSERT INTO PAIS(ISO, PAIS) VALUES('PF', 'Polinesia Francesa');
INSERT INTO PAIS(ISO, PAIS) VALUES('PL', 'Polonia');
INSERT INTO PAIS(ISO, PAIS) VALUES('PT', 'Portugal');
INSERT INTO PAIS(ISO, PAIS) VALUES('PR', 'Puerto Rico');
INSERT INTO PAIS(ISO, PAIS) VALUES('QA', 'Qatar');
INSERT INTO PAIS(ISO, PAIS) VALUES('GB', 'Reino Unido');
INSERT INTO PAIS(ISO, PAIS) VALUES('RE', 'Reunión');
INSERT INTO PAIS(ISO, PAIS) VALUES('RW', 'Ruanda');
INSERT INTO PAIS(ISO, PAIS) VALUES('RO', 'Rumania');
INSERT INTO PAIS(ISO, PAIS) VALUES('RU', 'Rusia');
INSERT INTO PAIS(ISO, PAIS) VALUES('EH', 'Sahara Occidental');
INSERT INTO PAIS(ISO, PAIS) VALUES('SB', 'Islas Salomón');
INSERT INTO PAIS(ISO, PAIS) VALUES('WS', 'Samoa');
INSERT INTO PAIS(ISO, PAIS) VALUES('AS', 'Samoa Americana');
INSERT INTO PAIS(ISO, PAIS) VALUES('KN', 'San Cristóbal y Nevis');
INSERT INTO PAIS(ISO, PAIS) VALUES('SM', 'San Marino');
INSERT INTO PAIS(ISO, PAIS) VALUES('PM', 'San Pedro y Miquelón');
INSERT INTO PAIS(ISO, PAIS) VALUES('VC', 'San Vicente y las Granadinas');
INSERT INTO PAIS(ISO, PAIS) VALUES('SH', 'Santa Helena');
INSERT INTO PAIS(ISO, PAIS) VALUES('LC', 'Santa Lucía');
INSERT INTO PAIS(ISO, PAIS) VALUES('ST', 'Santo Tomé y Príncipe');
INSERT INTO PAIS(ISO, PAIS) VALUES('SN', 'Senegal');
INSERT INTO PAIS(ISO, PAIS) VALUES('CS', 'Serbia y Montenegro');
INSERT INTO PAIS(ISO, PAIS) VALUES('SC', 'Seychelles');
INSERT INTO PAIS(ISO, PAIS) VALUES('SL', 'Sierra Leona');
INSERT INTO PAIS(ISO, PAIS) VALUES('SG', 'Singapur');
INSERT INTO PAIS(ISO, PAIS) VALUES('SY', 'Siria');
INSERT INTO PAIS(ISO, PAIS) VALUES('SO', 'Somalia');
INSERT INTO PAIS(ISO, PAIS) VALUES('LK', 'Sri Lanka');
INSERT INTO PAIS(ISO, PAIS) VALUES('SZ', 'Suazilandia');
INSERT INTO PAIS(ISO, PAIS) VALUES('ZA', 'Sudáfrica');
INSERT INTO PAIS(ISO, PAIS) VALUES('SD', 'Sudán');
INSERT INTO PAIS(ISO, PAIS) VALUES('SE', 'Suecia');
INSERT INTO PAIS(ISO, PAIS) VALUES('CH', 'Suiza');
INSERT INTO PAIS(ISO, PAIS) VALUES('SR', 'Surinam');
INSERT INTO PAIS(ISO, PAIS) VALUES('SJ', 'Svalbard y Jan Mayen');
INSERT INTO PAIS(ISO, PAIS) VALUES('TH', 'Tailandia');
INSERT INTO PAIS(ISO, PAIS) VALUES('TW', 'Taiwán');
INSERT INTO PAIS(ISO, PAIS) VALUES('TZ', 'Tanzania');
INSERT INTO PAIS(ISO, PAIS) VALUES('TJ', 'Tayikistán');
INSERT INTO PAIS(ISO, PAIS) VALUES('IO', 'Territorio Británico del Océano Índico');
INSERT INTO PAIS(ISO, PAIS) VALUES('TF', 'Territorios Australes Franceses');
INSERT INTO PAIS(ISO, PAIS) VALUES('TL', 'Timor Oriental');
INSERT INTO PAIS(ISO, PAIS) VALUES('TG', 'Togo');
INSERT INTO PAIS(ISO, PAIS) VALUES('TK', 'Tokelau');
INSERT INTO PAIS(ISO, PAIS) VALUES('TO', 'Tonga');
INSERT INTO PAIS(ISO, PAIS) VALUES('TT', 'Trinidad y Tobago');
INSERT INTO PAIS(ISO, PAIS) VALUES('TN', 'Túnez');
INSERT INTO PAIS(ISO, PAIS) VALUES('TC', 'Islas Turcas y Caicos');
INSERT INTO PAIS(ISO, PAIS) VALUES('TM', 'Turkmenistán');
INSERT INTO PAIS(ISO, PAIS) VALUES('TR', 'Turquía');
INSERT INTO PAIS(ISO, PAIS) VALUES('TV', 'Tuvalu');
INSERT INTO PAIS(ISO, PAIS) VALUES('UA', 'Ucrania');
INSERT INTO PAIS(ISO, PAIS) VALUES('UG', 'Uganda');
INSERT INTO PAIS(ISO, PAIS) VALUES('UY', 'Uruguay');
INSERT INTO PAIS(ISO, PAIS) VALUES('UZ', 'Uzbekistán');
INSERT INTO PAIS(ISO, PAIS) VALUES('VU', 'Vanuatu');
INSERT INTO PAIS(ISO, PAIS) VALUES('VE', 'Venezuela');
INSERT INTO PAIS(ISO, PAIS) VALUES('VN', 'Vietnam');
INSERT INTO PAIS(ISO, PAIS) VALUES('VG', 'Islas Vírgenes Británicas');
INSERT INTO PAIS(ISO, PAIS) VALUES('VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO PAIS(ISO, PAIS) VALUES('WF', 'Wallis y Futuna');
INSERT INTO PAIS(ISO, PAIS) VALUES('YE', 'Yemen');
INSERT INTO PAIS(ISO, PAIS) VALUES('DJ', 'Yibuti');
INSERT INTO PAIS(ISO, PAIS) VALUES('ZM', 'Zambia');
INSERT INTO PAIS(ISO, PAIS) VALUES('ZW', 'Zimbabue');

-- CLASIFICACION
INSERT INTO CLASIFICACION(CLASIFICACION, DESCRIPCION) VALUES ('AA','Películas para todo público que tengan además atractivo infantil y sean comprensibles para niños menores de siete años de edad.');
INSERT INTO CLASIFICACION(CLASIFICACION, DESCRIPCION) VALUES ('A','Películas para todo público.');
INSERT INTO CLASIFICACION(CLASIFICACION, DESCRIPCION) VALUES ('B','Películas para adolescentes de 12 años en adelante.');
INSERT INTO CLASIFICACION(CLASIFICACION, DESCRIPCION) VALUES ('B15','Película no recomendable para menores de 15 años de edad.');
INSERT INTO CLASIFICACION(CLASIFICACION, DESCRIPCION) VALUES ('C','Películas para adultos de 18 años en adelante.');
INSERT INTO CLASIFICACION(CLASIFICACION, DESCRIPCION) VALUES ('D','Películas para adultos, con sexo explícito, lenguaje procaz o alto grado de violencia.');

-- GENERO
INSERT INTO GENERO(GENERO) VALUES('Acción');
INSERT INTO GENERO(GENERO) VALUES('Ciencia Ficción');
INSERT INTO GENERO(GENERO) VALUES('Comedia');
INSERT INTO GENERO(GENERO) VALUES('Drama');
INSERT INTO GENERO(GENERO) VALUES('Fantasía');
INSERT INTO GENERO(GENERO) VALUES('Musical');
INSERT INTO GENERO(GENERO) VALUES('Rómantico');
INSERT INTO GENERO(GENERO) VALUES('Suspenso/Terror');

-- ESTADO
INSERT INTO ESTADO(DESCRIPCION) VALUES('Disponible'); -- ASIENTO
INSERT INTO ESTADO(DESCRIPCION) VALUES('No disponible'); -- ASIENTO
INSERT INTO ESTADO(DESCRIPCION) VALUES('Activa'); -- PROGRAMACION DE PROMOCION
INSERT INTO ESTADO(DESCRIPCION) VALUES('Inactiva'); -- PROGRAMACION DE PROMOCION
INSERT INTO ESTADO(DESCRIPCION) VALUES('Estreno'); -- PELICULA
INSERT INTO ESTADO(DESCRIPCION) VALUES('Pre-venta'); -- PELICULA
INSERT INTO ESTADO(DESCRIPCION) VALUES('Próximamente'); -- PELICULA
INSERT INTO ESTADO(DESCRIPCION) VALUES('En cartelera'); -- PELICULA


-- IDIOMA
INSERT INTO IDIOMA(NOMBRE) VALUES('Latino');
INSERT INTO IDIOMA(NOMBRE) VALUES('Original/Sub');

-- FORMATO 
INSERT INTO FORMATO(FORMATO) VALUES('2D');
INSERT INTO FORMATO(FORMATO) VALUES('3D');

-- CATEGORIA PROMOCIÓN
INSERT INTO CATEGORIA_PROMO(NOMBRE) VALUES('Dulcería');
INSERT INTO CATEGORIA_PROMO(NOMBRE) VALUES('Taquilla');

-- INSERCIONES SALA
INSERT INTO SALA(NOMBRE, DESCRIPCION, CANT_ASIENTOS, ID_ESTADO)
VALUES('1', 'Sala VIP', 65, 1);
INSERT INTO SALA(NOMBRE, DESCRIPCION, CANT_ASIENTOS, ID_ESTADO)
VALUES('2', 'Sala Platinum', 70, 1);
INSERT INTO SALA(NOMBRE, DESCRIPCION, CANT_ASIENTOS, ID_ESTADO)
VALUES('3', 'Sala Normal', 65, 1);

-- ASIENTOS
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('A20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('B20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('C20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('D20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('E20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('F20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('G20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('H20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('I20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('J20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('K20', 1, 1);

INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L1', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L2', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L3', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L4', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L5', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L6', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L7', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L8', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L9', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L10', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L11', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L12', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L13', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L14', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L15', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L16', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L17', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L18', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L19', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L20', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L21', 1, 1);
INSERT INTO ASIENTO(NUM_ASIENTO, ID_SALA, ID_ESTADO) VALUES('L22', 1, 1);

-- BOLETOS
INSERT INTO BOLETO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('ADULTREGULAR-HO','valor: L 98.00 + Cargo por servicio',98);
INSERT INTO BOLETO(NOMBRE, DESCRIPCION, PRECIO)
VALUES('CINEPACKPAREJA2D-HN','valido lunes a domingo, paga 2 entradas a precio de descuento. valor: L 170',170);

-- COMBOS
INSERT INTO COMBO(NOMBRE, DESCRIPCION, PRECIO, IMAGEN)
VALUES('HN-COMBO PERSONAL WK.', 'NUESTRO INMEJORABLE PORCORN TAMAÑO MEDIANO SALADITO MAS UNA SODA MEDIANA', 140, 'https://cinemarkmedia.modyocdn.com/ca/productos/8798.jpg');
INSERT INTO COMBO(NOMBRE, DESCRIPCION, PRECIO, IMAGEN)
VALUES('HN-COMBO 2WK.', 'RECIBE UN POPCORN SALADO GRANDE PARA COMPARTIR Y DOS SODAS MEDIANAS', 215, 'https://cinemarkmedia.modyocdn.com/ca/productos/8799.jpg');
INSERT INTO COMBO(NOMBRE, DESCRIPCION, PRECIO, IMAGEN)
VALUES('HN-COMBO PARA COMPARTIR WK', 'DOS POPCORNS MEDIANOS SALADITOS, DOS SODAS GRANDES UN CLASICOS HOTDOG Y UN NACHO', 364, 'https://cinemarkmedia.modyocdn.com/ca/productos/19388.jpg');
INSERT INTO COMBO(NOMBRE, DESCRIPCION, PRECIO, IMAGEN)
VALUES('HN-COMBO NACHO WK.', 'CRUJIENTES NACHOS, MAS UNA SODA MEDIANA Y UN POCORN SALADO MEDIANO', 217, 'https://cinemarkmedia.modyocdn.com/ca/productos/8976.jpg');
INSERT INTO COMBO(NOMBRE, DESCRIPCION, PRECIO, IMAGEN)
VALUES('HN-SODA GRANDE WK', 'DISFRUTA MAS SODA TAMAÑO GRANDE', 76, 'https://cinemarkmedia.modyocdn.com/ca/productos/8860.jpg');
INSERT INTO COMBO(NOMBRE, DESCRIPCION, PRECIO, IMAGEN)
VALUES('HN-SODA MEDIANA WK', 'REFRESCANTE Y DELICIOSA SODA TAMAÑO MEDIANO', 73, 'https://cinemarkmedia.modyocdn.com/ca/productos/8851.jpg');
INSERT INTO COMBO(NOMBRE, DESCRIPCION, PRECIO, IMAGEN)
VALUES('HN-AGUA WK.', 'REFRESCATE Y DISFRUTA EL SHOW', 37, 'https://cinemarkmedia.modyocdn.com/ca/productos/8801.jpg');