-- VER DETALLE BOLETOS QUE COMPRO UN USUARIO
SELECT ID_DETALLE, ID_FACTURA, ID_CARTELERA, BOLETO.NOMBRE NOMBRE_BOLETO, BUTACA
FROM DETALLE, BOLETO
WHERE ID_FACTURA = 2
AND DETALLE.ID_BOLETO = BOLETO.ID_BOLETO;

-- DETALLE COMPRA BOLETOS 1
SELECT BOLETO.NOMBRE NOMBRE_BOLETO, COUNT(BOLETO.ID_BOLETO) CANTIDAD, PRECIO, COUNT(BOLETO.ID_BOLETO)*PRECIO TOTAL
FROM DETALLE, BOLETO
WHERE ID_FACTURA = 2
AND DETALLE.ID_BOLETO = BOLETO.ID_BOLETO
AND DETALLE.ID_BOLETO = 1;

-- DETALLE COMPRA BOLETOS 2
SELECT BOLETO.NOMBRE NOMBRE_BOLETO, ROUND(COUNT(BOLETO.ID_BOLETO)/2,0) CANTIDAD, PRECIO, ROUND(COUNT(BOLETO.ID_BOLETO)/2,0)*PRECIO TOTAL
FROM DETALLE, BOLETO
WHERE ID_FACTURA = 2
AND DETALLE.ID_BOLETO = BOLETO.ID_BOLETO
AND DETALLE.ID_BOLETO = 2;

-- VER DETALLE COMBOS QUE COMPRO UN USUARIO
SELECT ID_DETALLE, ID_FACTURA, ID_CARTELERA, COMBO.NOMBRE NOMBRE_COMBO
FROM DETALLE, COMBO
WHERE ID_FACTURA = 2
AND DETALLE.ID_COMBO = COMBO.ID_COMBO;

-- VER COMBOS Y CANTIDAD
SELECT COMBO.NOMBRE NOMBRE_COMBO, COUNT(DETALLE.ID_COMBO) CANTIDAD, COMBO.PRECIO, COUNT(DETALLE.ID_COMBO)*PRECIO TOTAL
FROM DETALLE, COMBO
WHERE ID_FACTURA = 2
AND DETALLE.ID_COMBO = COMBO.ID_COMBO
GROUP BY DETALLE.ID_COMBO;

-- TICKETS BOLETO
SELECT TITULO, IDIOMA.NOMBRE IDIOMA, FORMATO, CLASIFICACION, FECHA, HORA_INICIO, BOLETO.NOMBRE NOMBRE_BOLETO, PRECIO, BUTACA
FROM PELICULA, IDIOMA, FORMATO, DETALLE, CLASIFICACION, CARTELERA, BOLETO
WHERE PELICULA.ID_PELICULA = CARTELERA.ID_PELICULA
AND DETALLE.ID_CARTELERA = CARTELERA.ID_CARTELERA
AND IDIOMA.ID_IDIOMA = CARTELERA.ID_IDIOMA
AND CLASIFICACION.ID_CLASIFICACION = PELICULA.ID_CLASIFICACION
AND FORMATO.ID_FORMATO = CARTELERA.ID_FORMATO
AND DETALLE.ID_BOLETO = BOLETO.ID_BOLETO
AND ID_FACTURA = 2;

-- LIBRO DE VENTAS
SELECT F.ID_FACTURA AS IdFactura, P.TITULO, B.PRECIO, SUM(F.SUBTOTAL) AS Subtotal, SUM(F.TOTAL) AS Total , F.FECHA FROM FACTURA F 
INNER JOIN DETALLE D ON D.ID_FACTURA = F.ID_FACTURA 
inner join CARTELERA C on C.ID_CARTELERA = D.ID_CARTELERA 
inner join PELICULA P on P.ID_PELICULA = C.ID_PELICULA
inner join BOLETO B on B.ID_BOLETO = D.ID_BOLETO
group by F.ID_FACTURA;